controller_list:
  - name: fake_rgt_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - rgt_panda_joint1
      - rgt_panda_joint2
      - rgt_panda_joint3
      - rgt_panda_joint4
      - rgt_panda_joint5
      - rgt_panda_joint6
      - rgt_panda_joint7
  - name: fake_rgt_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - rgt_panda_finger_joint1
initial:  # Define initial robot poses per group
  - group: rgt_arm
    pose: ready
  - group: rgt_hand
    pose: close