rgt_arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - rgt_panda_joint1
    - rgt_panda_joint2
    - rgt_panda_joint3
    - rgt_panda_joint4
    - rgt_panda_joint5
    - rgt_panda_joint6
    - rgt_panda_joint7
  gains:
    rgt_panda_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_panda_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_panda_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_panda_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_panda_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_panda_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_panda_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1