joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50  
   
right_arm_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - right_arm_joint1
    - right_arm_joint2
    - right_arm_joint3
    - right_arm_joint4
    - right_arm_joint5
    - right_arm_joint6
    - right_arm_joint7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_arm_joint1: {trajectory: 0.1, goal: 0.1}
      right_arm_joint2: {trajectory: 0.1, goal: 0.1}
      right_arm_joint3: {trajectory: 0.1, goal: 0.1}
      right_arm_joint4: {trajectory: 0.1, goal: 0.1}
      right_arm_joint5: {trajectory: 0.1, goal: 0.1}
      right_arm_joint6: {trajectory: 0.1, goal: 0.1}
      right_arm_joint7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

left_arm_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - left_arm_joint1
    - left_arm_joint2
    - left_arm_joint3
    - left_arm_joint4
    - left_arm_joint5
    - left_arm_joint6
    - left_arm_joint7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_arm_joint1: {trajectory: 0.1, goal: 0.1}
      left_arm_joint2: {trajectory: 0.1, goal: 0.1}
      left_arm_joint3: {trajectory: 0.1, goal: 0.1}
      left_arm_joint4: {trajectory: 0.1, goal: 0.1}
      left_arm_joint5: {trajectory: 0.1, goal: 0.1}
      left_arm_joint6: {trajectory: 0.1, goal: 0.1}
      left_arm_joint7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

#notice that the grippers joint2 mimics joint1
#this is why it is not listed under the hand controllers
right_hand_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - right_arm_finger_joint1
  gains:
    right_arm_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

left_hand_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - left_arm_finger_joint1
  gains:
    left_arm_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}