rgt_arm_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rgt_arm_joint1
    - rgt_arm_joint2
    - rgt_arm_joint3
    - rgt_arm_joint4
    - rgt_arm_joint5
    - rgt_arm_joint6
    - rgt_arm_joint7
  gains:
    rgt_arm_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_arm_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_arm_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_arm_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_arm_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_arm_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rgt_arm_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

lft_arm_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - lft_arm_joint1
    - lft_arm_joint2
    - lft_arm_joint3
    - lft_arm_joint4
    - lft_arm_joint5
    - lft_arm_joint6
    - lft_arm_joint7
  gains:
    lft_arm_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lft_arm_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lft_arm_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lft_arm_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lft_arm_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lft_arm_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lft_arm_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

#notice that the grippers joint2 mimics joint1
rgt_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rgt_arm_finger_joint1
  gains:
    rgt_arm_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

lft_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - lft_arm_finger_joint1
  gains:
    lft_arm_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1