controller_list:
  - name: rgt_arm_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - rgt_arm_joint1
      - rgt_arm_joint2
      - rgt_arm_joint3
      - rgt_arm_joint4
      - rgt_arm_joint5
      - rgt_arm_joint6
      - rgt_arm_joint7
  - name: lft_arm_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - lft_arm_joint1
      - lft_arm_joint2
      - lft_arm_joint3
      - lft_arm_joint4
      - lft_arm_joint5
      - lft_arm_joint6
      - lft_arm_joint7

#notice that the grippers joint2 mimics joint1
  - name: rgt_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rgt_arm_finger_joint1

  - name: lft_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - lft_arm_finger_joint1