rgt_arm_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - rgt_arm_joint1
    - rgt_arm_joint2
    - rgt_arm_joint3
    - rgt_arm_joint4
    - rgt_arm_joint5
    - rgt_arm_joint6
    - rgt_arm_joint7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      rgt_arm_joint1: {trajectory: 0.1, goal: 0.1}
      rgt_arm_joint2: {trajectory: 0.1, goal: 0.1}
      rgt_arm_joint3: {trajectory: 0.1, goal: 0.1}
      rgt_arm_joint4: {trajectory: 0.1, goal: 0.1}
      rgt_arm_joint5: {trajectory: 0.1, goal: 0.1}
      rgt_arm_joint6: {trajectory: 0.1, goal: 0.1}
      rgt_arm_joint7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

lft_arm_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - lft_arm_joint1
    - lft_arm_joint2
    - lft_arm_joint3
    - lft_arm_joint4
    - lft_arm_joint5
    - lft_arm_joint6
    - lft_arm_joint7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      lft_arm_joint1: {trajectory: 0.1, goal: 0.1}
      lft_arm_joint2: {trajectory: 0.1, goal: 0.1}
      lft_arm_joint3: {trajectory: 0.1, goal: 0.1}
      lft_arm_joint4: {trajectory: 0.1, goal: 0.1}
      lft_arm_joint5: {trajectory: 0.1, goal: 0.1}
      lft_arm_joint6: {trajectory: 0.1, goal: 0.1}
      lft_arm_joint7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

#notice that the grippers joint2 mimics joint1
#this is why it is not listed under the hand controllers
rgt_hand_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - rgt_arm_finger_joint1
  gains:
    rgt_arm_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

lft_hand_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - lft_arm_finger_joint1
  gains:
    lft_arm_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}