panda_multiple_arms:
  rgt_panda_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - rgt_panda_joint1
      - rgt_panda_joint2
      - rgt_panda_joint3
      - rgt_panda_joint4
      - rgt_panda_joint5
      - rgt_panda_joint6
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        rgt_panda_joint1: {trajectory: 0.1, goal: 0.1}
        rgt_panda_joint2: {trajectory: 0.1, goal: 0.1}
        rgt_panda_joint3: {trajectory: 0.1, goal: 0.1}
        rgt_panda_joint4: {trajectory: 0.1, goal: 0.1}
        rgt_panda_joint5: {trajectory: 0.1, goal: 0.1}
        rgt_panda_joint6: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  lft_panda_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - lft_panda_joint1
      - lft_panda_joint2
      - lft_panda_joint3
      - lft_panda_joint4
      - lft_panda_joint5
      - lft_panda_joint6
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        lft_panda_joint1: {trajectory: 0.1, goal: 0.1}
        lft_panda_joint2: {trajectory: 0.1, goal: 0.1}
        lft_panda_joint3: {trajectory: 0.1, goal: 0.1}
        lft_panda_joint4: {trajectory: 0.1, goal: 0.1}
        lft_panda_joint5: {trajectory: 0.1, goal: 0.1}
        lft_panda_joint6: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10